export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const SET_FORM_STATE = 'SET_FORM_STATE'
export const INCREMENT_COUNT = "INCREMENT_COUNT"
export const DECEREMENT_COUNT = "DECEREMENT_COUNT"
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const ADD_TO_CART = 'ADD_TO_CART';

export const RESET_COUNT = 'RESET_COUNT'

export const INCREMENT_ITEM_COUNT = 'INCREMENT_ITEM_COUNT';
export const DECREMENT_ITEM_COUNT = 'DECREMENT_ITEM_COUNT'; 

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const SET_FORM_FIELD = 'SET_FORM_FIELD';
export const VALIDATE_FORM= "VALIDATE_FORM";